api/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.PostListView.as_view(),  name="list"),
    url(r'^create/$', views.PostCreateView.as_view(),  name="create"),
    url(r'^(?P<post_slug>[-\w]+)/detail/$', views.PostDetailView.as_view(),  name="detail"),
    url(r'^(?P<post_slug>[-\w]+)/delete/$', views.PostDeleteView.as_view(),  name="delete"),
    url(r'^(?P<post_slug>[-\w]+)/update/$', views.PostUpdateView.as_view(),  name="update"),
    url(r'^comments/$', views.CommentListView.as_view(),  name="comment-list"),
   	url(r'^comments/create$', views.CommentCreateView.as_view(),  name="comment-create"),
   	url(r'^register/$', views.UserCreateView.as_view(),  name="register"),
   	url(r'^login/$', views.UserLoginView.as_view(),  name="login"),
]

blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^more/', include('posts.urls', namespace="more")),
    url(r'^comments/', include('django_comments.urls')),
    url(r'^googly/', include('googly.urls', namespace="googly")),
    url(r'^api/', include('api.urls', namespace="api")),
    

]

if settings.DEBUG:
	urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^anything/$', views.some_function, name="anything"),
    url(r'^list/$', views.post_list, name="list"),
    url(r'^detail/(?P<post_slug>[-\w]+)/$', views.post_detail, name="detail"),

    url(r'^create/$', views.post_create, name="create"),
    url(r'^update/(?P<post_slug>[-\w]+)/$', views.post_update, name="update"),
    url(r'^delete/(?P<post_slug>[-\w]+)/$', views.post_delete, name="delete"),
    url(r'^random/$', views.random, name="random"),

    url(r'^like_button/(?P<post_id>\d+)/$', views.like_button, name="like_button"),
    url(r'^signup/$', views.usersignup, name="signup"),
    url(r'^login/$', views.userlogin, name="login"),
    url(r'^logout/$', views.userlogout, name="logout"),

]

posts/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.db.models.signals import pre_save
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

class Post(models.Model):
	title = models.CharField(max_length=120)
	author = models.ForeignKey(User, default=1)
	slug = models.SlugField(unique=True)
	content = models.TextField()
	created = models.DateTimeField(auto_now_add=True)
	draft = models.BooleanField(default=False)
	publish_date = models.DateField()
	img = models.ImageField(null=True, blank=True, upload_to="post_images")

	def __str__(self):
		return self.title

	def get_detail_url(self):
		return reverse("more:detail", kwargs={"post_slug":self.slug})

	class Meta:
		ordering = ['title']


def create_slug(instance, new_slug=None):
	slug_value = slugify(instance.title)
	if new_slug is not None:
		slug_value = new_slug
	
	query = Post.objects.filter(slug=slug_value)
	if query.exists():
		slug_value = "%s-%s"%(slug_value, query.last().id)
		return create_slug(instance, new_slug=slug_value)
	return slug_value


def pre_save_post_function(*args, **kwargs):
	instance = kwargs['instance']
	if not instance.slug:
		instance.slug = create_slug(instance)

pre_save.connect(pre_save_post_function, sender=Post)

class Like(models.Model):
	user = models.ForeignKey(User)
	post = models.ForeignKey(Post)
	timestamp = models.DateTimeField(auto_now_add=True)

posts/forms.py
from django import forms
from .models import Post
from django.contrib.auth.models import User


class PostForm(forms.ModelForm):
	class Meta:
		model = Post
		fields = ['title', 'content', 'img', 'draft', 'publish_date']

		widgets = {
			'publish_date': forms.DateInput(attrs={"type":"date"}),
		}

class UserSignup(forms.ModelForm):
	class Meta:
		model = User
		fields = ['username', 'email', 'password']

		widgets = {
			'password': forms.PasswordInput(),
		}

class UserLogin(forms.Form):
	username = forms.CharField(required=True)
	password = forms.CharField(required=True, widget=forms.PasswordInput())

posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Like
from .forms import PostForm, UserSignup, UserLogin
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import Http404, JsonResponse
from django.utils import timezone
from django.db.models import Q
from django.contrib.auth import login, logout, authenticate

def usersignup(request):
    context = {}
    form = UserSignup()
    context['form'] = form

    if request.method == "POST":
        form = UserSignup(request.POST)
        if form.is_valid():
            user = form.save()
            x = user.username
            y = user.password
            user.set_password(y)
            user.save()
            auth = authenticate(username=x, password=y)
            login(request, auth)
            return redirect("more:list")
        messages.warning(request, form.errors)
        return redirect("more:signup")
    return render(request, 'signup.html', context)

def userlogin(request):
    context = {}
    form = UserLogin()
    context['form'] = form
    if request.method == "POST":
        form = UserLogin(request.POST)
        if form.is_valid():
            some_username = form.cleaned_data['username']
            some_password = form.cleaned_data['password']
            auth = authenticate(username=some_username, password=some_password)
            if auth is not None:
                login(request, auth)
                return redirect("more:list")
            messages.warning(request, 'Incorrect Username/Password combination. *cough cough* noob.')
            return redirect("more:login")
        messages.warning(request, form.errors)
        return redirect("more:login")
    return render(request, 'login.html', context)

def userlogout(request):
    logout(request)
    return redirect("more:login")

def random(request):
    return render(request, 'random.html')

def post_create(request):
    if not request.user.is_staff:
        raise Http404
    form = PostForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        hamzas_post = form.save(commit=False)
        hamzas_post.author = request.user
        hamzas_post.save()
        messages.success(request, "Awesome, you just added a blog post!")
        return redirect("more:list")
    context = {
        "form": form,
    }
    return render(request, 'post_create.html', context)

def post_update(request, post_slug):
    if not request.user.is_staff:
        raise Http404
    item = Post.objects.get(slug=post_slug)
    form = PostForm(request.POST or None, request.FILES or None, instance=item)
    if form.is_valid():
        form.save()
        messages.info(request, "Hey, you just changed a blog post!")
        return redirect("more:detail", post_slug=item.slug)
    context = {
        "form": form,
        "item":item,
    }
    return render(request, 'post_update.html', context)

def post_delete(request, post_slug):
    if not request.user.is_staff:
        raise Http404
    Post.objects.get(slug=post_slug).delete()
    messages.warning(request, "Noooooooooo!")
    return redirect("more:list")

def some_function(request):
    some_dictionary = {
        "some_key": "with a random value",
    }
    return render(request, "something.html", some_dictionary)


def post_list(request):
    today = timezone.now().date()

    objects = Post.objects.filter(draft=False, publish_date__lte=today)
    if request.user.is_staff:
        objects=Post.objects.all()


    query = request.GET.get('q')
    if query:
        objects = objects.filter(
            Q(title__icontains=query)|
            Q(content__icontains=query)|
            Q(author__first_name__icontains=query)|
            Q(author__last_name__icontains=query)
            ).distinct()

    paginator = Paginator(objects, 4)

    number = request.GET.get('page')

    try:
        objects = paginator.page(number)
    except PageNotAnInteger:
        objects = paginator.page(1)
    except EmptyPage:
        objects = paginator.page(paginator.num_pages)

    context = {
        "post_items": objects,
        "today":today,
    }
    return render(request, "list.html", context)

def post_detail(request, post_slug):
    today = timezone.now().date()
    item = get_object_or_404(Post, slug=post_slug)

    liked = False
    if not request.user.is_staff:
        if item.draft or item.publish_date > today:
            raise Http404

    if request.user.is_authenticated():
        if Like.objects.filter(post=item, user=request.user).exists():
            liked = True
        else:
            liked = False

    like_count = item.like_set.count()

    context = {
        "item": item,
        "liked": liked,
        "like_count": like_count,
    }
    return render(request, "detail.html", context)


def like_button(request, post_id):
    post_object = Post.objects.get(id=post_id)

    like, created = Like.objects.get_or_create(user=request.user, post=post_object)

    if created:
        action = "like"
    else:
        like.delete()
        action = "unlike"

    like_count = post_object.like_set.count()
    response = {
        "like_count":like_count,
        "action":action,
    }
    return JsonResponse(response, safe=False)

posts/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<meta charset="UTF-8">
	<title>
		{% block heading %}
			
		{% endblock heading %}
	</title>
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
{% include "navbar.html" %}
{% include "messages.html" %}

<br>
<div class="container">
{% block content %}
	
{% endblock content %}
</div>
<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'js/popper.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script>
		$(function () {
	  $('[data-toggle="popover"]').popover()
	})

</script>
</body>
</html>

posts/templates/comments.html
{% load crispy_forms_tags %}
{% load comments %}

{% get_comment_list for item as comments %}

{% for awesome in comments %}
	 <div class="alert alert-info" role="alert"><b>{{ awesome.user_name }} said:</b> {{ awesome.comment|linebreaks}}</div>
{% endfor %}

{% get_comment_form for item as form %}

{% if not request.user.is_authenticated %}
	<h1>Please Log in to comment</h1>
{% else %}
	<form action="{% comment_form_target %}" method="POST">
		{% csrf_token %}
		
		<input type="hidden" name="name" value="{{request.user.username}}">
		<input type="hidden" name="email" value="{{request.user.email}}">
		<input type="text" name="comment" class="form-control input-lg">
		{{form.content_type}}
		{{form.object_pk}}
		{{form.timestamp}}
		{{form.security_hash}}
		
		<input type="hidden" name="next" value="{{item.get_detail_url}}">
		<input type="submit" value="Submit" class="btn btn-outline-info">
	</form>
{% endif %}

posts/templates/detail.html
{% extends "base.html" %}
{% load share %}

{% block heading %}
	Detail
{% endblock heading %}

{% block content %}
	<div class="card text-center">
	  <div class="card-header">
	    Blog Post
	  </div>
	  <div class="card-body">
	    <h4 class="card-title">{{item.title}}</h4>
	    <p class="card-text">{{item.content}}</p>
	    <a class="btn btn-primary" href="https://www.facebook.com/sharer/sharer.php?u={{request.build_absolute_uri}}">
		<i class="fa fa-facebook" aria-hidden="true"></i>
		</a>
		<a class="btn btn-info" href="https://twitter.com/home?status={{item.content|truncatechars:140|share}}%20{{request.build_absolute_uri}}">
		<i class="fa fa-twitter" aria-hidden="true"></i>
		</a>			
		<a class="btn btn-primary" href="https://www.linkedin.com/shareArticle?mini=true&url={{request.build_absolute_uri}}&title={{item.title|share}}&summary={{item.content|share}}&source={{request.build_absolute_uri}}">
		<i class="fa fa-linkedin" aria-hidden="true"></i>
		</a>
	  </div>
	  <div class="card-footer text-muted">
	    {{item.publish_date}}
	  </div>
	</div>
	<br>
	<div class="btn btn-secondary" onclick="ajax_like()">
		<span id="likes_count">{{like_count}}</span>
		<span><i id="heart" class="fa fa-heart {% if liked %}text-danger{% endif %}" aria-hidden="true"></i></span>
	</div>
	<br><br>
	{% include "comments.html" %}

	<script>
		function ajax_like()
		{
			$.ajax(
				{
					type:'GET',
					url:'{% url "more:like_button" post_id=item.id %}',
					error:function(){
						console.log("OMGGG WHAT did you do?!");
					} ,
					success:function(data){
						$("#likes_count").text(data.like_count);
						if(data.action==="like"){
							$("#heart").addClass("text-danger");
						}
						else{
							$("#heart").removeClass("text-danger");
						}
					},
				});
		}
	</script>
{% endblock content %}

posts/templates/list.html
{% extends "base.html" %}
{% block heading %}
	List
{% endblock heading %}

{% block content %}
	
	<div class="jumbotron">
		<h1 class="display-3">These are my posts!</h1>
	</div>
	
	<div class="row">
	{% for item in post_items %}
		<div class="card col-xs-12 col-md-6" style="width: 20rem;">
			{% if item.img %}
				<img class="card-img-top" src="{{item.img.url}}" alt="Card image cap">
			{% endif %}
			<div class="card-body">
				<h4 class="card-title">
					{{item.title}}
					<small>{{item.publish_date|timesince}}</small>
					{% if item.draft %}
						<span class="text-danger">Draft</span>
					{% endif %}
					{% if item.publish_date > today %}
						<span class="text-success">Future Post</span>
					{% endif %}
				</h4>
				<p class="card-text">{{item.content|linebreaks|truncatechars:30}}</p>
				<p class="card-text">{{item.author.username}}</p>
				<p class="card-text">{{item.author.get_full_name}}</p>
				<p class="card-text">{{item.author.last_login}}</p>
				<p class="card-text">{{item.author.date_joined}}</p>
				<a href="{% url 'more:detail' post_slug=item.slug %}" class="btn btn-info">Read More <i class="fa fa-book" aria-hidden="true"></i></a>
				<a href="{% url 'more:update' post_slug=item.slug %}" class="btn btn-warning">Update <i class="fa fa-pencil" aria-hidden="true"></i></a>
				<a href="{% url 'more:delete' post_slug=item.slug %}" class="btn btn-danger">Delete <i class="fa fa-trash" aria-hidden="true"></i></a>

			</div>
		</div>
	{% empty %}
		<h1 class="text-danger">Sorry, there are no results for {{request.GET.q}}</h1>
	{% endfor %}
	</div>
	<div class="pagination">
    <span class="step-links">
        {% if post_items.has_previous %}
            <a href="?page={{ post_items.previous_page_number }}&q={{request.GET.q}}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ post_items.number }} of {{ post_items.paginator.num_pages }}.
        </span>

        {% if post_items.has_next %}
            <a href="?page={{ post_items.next_page_number }}&q={{request.GET.q}}">next</a>
        {% endif %}
    </span>
	</div>
{% endblock content %}

posts/templates/login.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block heading %}
	Login
{% endblock heading %}

{% block content %}
	<form action="{% url 'more:login' %}" method="POST">
		{% csrf_token %}
		{{form|crispy}}
		<input class="btn btn-success" type="submit" value="Login Now!">
	</form>
{% endblock content %}

posts/templates/messages.html
{% if messages %}
<div class="messages">
    {% for message in messages %}
    <div{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</div>
    {% endfor %}
</div>
{% endif %}

posts/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'more:list' %}">Hamza's Blog</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'more:list' %}">Home<span class="sr-only">(current)</span></a>
      </li>
      {% if request.user.is_staff %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'more:create' %}">Create Post</a>
        </li>
      {% endif %}
      {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'more:logout' %}">Logout</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">{{request.user}}</a>
        </li>
      {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'more:login' %}">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'more:signup' %}">Signup</a>
        </li>
      {% endif %}
    </ul>
    <form class="form-inline my-2 my-lg-0" action="{% url 'more:list' %}" method="GET">
      <input class="form-control mr-sm-2" name='q' type="search" placeholder="Search" aria-label="Search" value="{{request.GET.q}}">
      <button class="btn btn-outline-info my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

posts/templates/post_create.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block heading %}
	Create
{% endblock heading %}

{% block content %}
	<form action="{% url 'more:create' %}" method="POST" enctype="multipart/form-data">
		{% csrf_token %}
		{{form|crispy}}
		<input class="btn btn-success" type="submit" value="Create">
	</form>
{% endblock content %}

posts/templates/post_update.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block heading %}
	Update
{% endblock heading %}

{% block content %}
	<form action="{% url 'more:update' post_slug=item.slug %}" method="POST" enctype="multipart/form-data">
		{% csrf_token %}
		{{form|crispy}}
		<input type="submit" value="Update">
	</form>
{% endblock content %}
</html>

posts/templates/random.html
{% extends "base.html" %}


{% block content %}
  
<style>
  .blue{
    background-color: blue;
    color: white;
  }
  .green{
    background-color: green;
    color: white;
  }
</style>


<div class="row">
  <div class="col-xs-12 col-sm-12 col-md-6 col-lg-4 blue">heloo</div>
  <div class="col-xs-12 col-sm-12 col-md-6 col-lg-4 green">heloo</div>
  <div class="col-xs-12 col-sm-12 col-md-6 col-lg-4 blue">heloo</div>
</div>


{% endblock content %}

posts/templates/signup.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block heading %}
	Signup
{% endblock heading %}

{% block content %}
	<form action="{% url 'more:signup' %}" method="POST">
		{% csrf_token %}
		{{form|crispy}}
		<input class="btn btn-success" type="submit" value="Signup Now!">
	</form>
{% endblock content %}

posts/templates/something.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
</head>
<body>
	{{some_key}}
</body>
</html>