api/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.PostListView.as_view(),  name="list"),
    url(r'^create/$', views.PostCreateView.as_view(),  name="create"),
    url(r'^(?P<post_slug>[-\w]+)/detail/$', views.PostDetailView.as_view(),  name="detail"),
    url(r'^(?P<post_slug>[-\w]+)/delete/$', views.PostDeleteView.as_view(),  name="delete"),
    url(r'^(?P<post_slug>[-\w]+)/update/$', views.PostUpdateView.as_view(),  name="update"),
    url(r'^comments/$', views.CommentListView.as_view(),  name="comment-list"),
   	url(r'^comments/create$', views.CommentCreateView.as_view(),  name="comment-create"),
   	url(r'^register/$', views.UserCreateView.as_view(),  name="register"),
   	url(r'^login/$', views.UserLoginView.as_view(),  name="login"),
]

blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^more/', include('posts.urls', namespace="more")),
    url(r'^comments/', include('django_comments.urls')),
    url(r'^googly/', include('googly.urls', namespace="googly")),
    url(r'^api/', include('api.urls', namespace="api")),
    

]

if settings.DEBUG:
	urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

googly/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^place/search/$', views.place_text_search, name="place-search"),
    url(r'^place/detail/$', views.place_detail, name="place-detail"),
]

googly/models.py
from django.db import models

# Create your models here.

googly/views.py
from django.http import JsonResponse
from django.shortcuts import render
import requests

def place_text_search(request):
	key = "AIzaSyATAFLFSnKUFSYOH5p-LINwRwhyMc9Pd-U"
	query = request.GET.get('query', 'coded')
	url = "https://maps.googleapis.com/maps/api/place/textsearch/json?query=%s&region=kw&key=%s"%(query, key)

	next_page = request.GET.get('nextpage')
	if next_page is not None:
		url += "&pagetoken="+next_page

	response = requests.get(url)

	context = {
	"response": response.json()
	}
	return render(request, 'places_search.html', context)
	# return JsonResponse( response.json(), safe=False)

def place_detail(request):
	key = "AIzaSyATAFLFSnKUFSYOH5p-LINwRwhyMc9Pd-U"
	mapkey = "AIzaSyBg4zdZNrCn7-2GPTQsnkfboO2YLOD5BKE"
	place_id = request.GET.get('place_id','')
	url = "https://maps.googleapis.com/maps/api/place/details/json?key=%s&placeid=%s"%(key, place_id)

	response = requests.get(url)
	context = {
	"response": response.json(),
	"map": mapkey
	}
	return render(request, 'place_detail.html', context)
	#return JsonResponse( response.json(), safe=False)

googly/templates/place_detail.html
{% extends "base.html" %}

{% block content %}
<div class="card">
  <h4 class = "card-header">{{response.result.vicinity}}</h4>
  <div class = "class-body">
    <h4 class="card-title">{{response.result.name}}</h4>
    <p class="card-text">Address:{{response.result.formatted_address}}</p>
    <a href="{{response.result.url}}" class="btn btn-danger"><i class="fa fa-map-marker" area-hidden="true"></i><a/>

  </div>

</div>
<iframe
  id = "map"
  width="600"
  height="450"
  frameborder="0" style="border:0"
  src="" allowfullscreen>

<script>

 function do_something(lat, lng){
   var map = ${"#map"}
   map.attr(
      'srs', 
      'https://www.google.com/maps/embed/v1/directions?key={{map}}&origin='+lat+","+lng+'&destination={{response.result.geometry.location.lat}},{{response.result.geometry.location.lng}}'

    )

 }

  navigator.geolocation.getCurrentPosition(function(position) {
  do_something(position.coords.latitude, position.coords.longitude);
  });

</script>

</iframe>
{% endblock content %}

googly/templates/places_search.html
{% extends "base.html" %}

{% block content %}
<form action="{% url 'googly:place-search' %}" method="GET">
  <div class="col-lg-6">
    <div class="input-group">
      <input type="text" class="form-control" placeholder="Search for..." aria-label="Search for..." name="query">
      <span class="input-group-btn">
        <button class="btn btn-secondary" type="submit">Search</button>
      </span>
    </div>
  </div>
</form>
<br>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Address</th>
      <th scope="col">Detail</th>
    </tr>
  </thead>
  <tbody>
  	{% for place in response.results %}
    <tr>
      <td>{{place.name}}</td>
      <td>{{place.formatted_address}}</td>
      <td>
      	<form action="{% url 'googly:place-detail' %}" method="GET">
      		<input type="hidden" name="place_id" value='{{place.place_id}}'>
    		<input type="submit" value="Detail" class="btn btn-outline-info">
      	</form>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% if response.next_page_token %}
    <form action="{% url 'googly:place-search' %}" method="GET">
    	<input type="hidden" name="nextpage" value='{{response.next_page_token}}'>
    	<input type="submit" value="More Results..." class="btn btn-outline-info">
    </form>	
{% endif %}
{% endblock content %}